# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from welcome import Ui_MainWindow
from signup import MyUi_Dialog
import sqlite3
import Auth


class Ui_Dialog(object):
    
    def signupWindowShow(self):
        self.signupWindow = QtWidgets.QDialog()
        self.ui = MyUi_Dialog()
        self.ui.setupUi(self.signupWindow)
        self.signupWindow.show()  
        
    def showMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Warning)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_()  
    
    def showsuccessMessageBox(self,title,message):
        msgBox = QtWidgets.QMessageBox()
        msgBox.setIcon(QtWidgets.QMessageBox.Success)
        msgBox.setWindowTitle(title)
        msgBox.setText(message)
        msgBox.setStandardButtons(QtWidgets.QMessageBox.Ok)
        msgBox.exec_() 
    
    def welcomeWindowShow(self):
        self.welcomeWindow = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.welcomeWindow)
        self.welcomeWindow.show()      
        
    def loginCheck(self):
        #print("Login Button Clicked !")
        u = self.uname_lineEdit.text()
        p = self.password_lineEdit.text()
        result = Auth.login(u,p)
        #print("User found !")
        if result ['status']=='success':
            self.welcomeWindowShow()
        else:
            print("Incorrect username or password please try again")
            self.showMessageBox('Warning','Invalid Username or Password Please try again')
        
     
    def signUpCheck(self):
        self.signupWindowShow()
        #import Auth
        #print("Sign up Button Clicked !")
        #u = self.uname_lineEdit.text()
        #p = self.password_lineEdit.text()
        #result = Auth.signup(u,p)
        #if result ['status']=='success':
            #self.showMessageBox('Success','Account has been created')
        
        
    def passwordCheck(self):
        print("Forgot Password Clicked !")
        
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(813, 539)
        Dialog.setStyleSheet("background-color: rgb(14, 32, 40);")
        self.u_name_label = QtWidgets.QLabel(Dialog)
        self.u_name_label.setGeometry(QtCore.QRect(260, 240, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.u_name_label.setFont(font)
        self.u_name_label.setStyleSheet("color: rgb(231, 236, 247);")
        self.u_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.u_name_label.setObjectName("u_name_label")
        self.pass_label = QtWidgets.QLabel(Dialog)
        self.pass_label.setGeometry(QtCore.QRect(260, 300, 101, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pass_label.setFont(font)
        self.pass_label.setStyleSheet("color: rgb(231, 236, 247);")
        self.pass_label.setMidLineWidth(1)
        self.pass_label.setAlignment(QtCore.Qt.AlignCenter)
        self.pass_label.setObjectName("pass_label")
        self.uname_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.uname_lineEdit.setGeometry(QtCore.QRect(380, 240, 181, 21))
        self.uname_lineEdit.setStyleSheet("background-color: rgb(240, 251, 239);")
        self.uname_lineEdit.setText("")
        self.uname_lineEdit.setObjectName("uname_lineEdit")
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.password_lineEdit.setGeometry(QtCore.QRect(380, 300, 181, 21))
        self.password_lineEdit.setStyleSheet("background-color: rgb(240, 251, 239);")
        self.password_lineEdit.setInputMask("")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.signup_btn = QtWidgets.QPushButton(Dialog)
        self.signup_btn.setGeometry(QtCore.QRect(300, 370, 71, 21))
        self.signup_btn.setStyleSheet("QPushButton#signup_btn{\n"
"background-color:rgba(2,65,118,255);\n"
"background-color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#signup_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(255, 255, 255);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#signup_btn:hover{\n"
"background-color:rgb(255, 255, 255);}")
        self.signup_btn.setObjectName("signup_btn")
        self.signup_btn.clicked.connect(self.signUpCheck)
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(420, 370, 141, 21))
        self.pushButton_2.setStyleSheet("QPushButton#pushButton_2{\n"
"background-color:rgba(2,65,118,255);\n"
"background-color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#pushButton_2:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(255, 255, 255);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#pushButton_2:hover{\n"
"background-color:rgb(255, 255, 255);}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.passwordCheck)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(190, 370, 101, 21))
        self.label.setStyleSheet("color: rgb(231, 236, 247);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.login_btn = QtWidgets.QPushButton(Dialog)
        self.login_btn.setGeometry(QtCore.QRect(310, 430, 191, 31))
        self.login_btn.setStyleSheet("QPushButton#login_btn{\n"
"background-color:rgba(2,65,118,255);\n"
"background-color:rgba(255,255,255,200);\n"
"border-radius:10px;\n"
"}\n"
"QPushButton#login_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgb(255, 255, 255);\n"
"background-position:calc(100%-10px)center;\n"
"}\n"
"QPushButton#login_btn:hover{\n"
"background-color:rgb(255, 255, 255);}")
        self.login_btn.setObjectName("login_btn")
        self.login_btn.clicked.connect(self.loginCheck)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(320, 50, 171, 141))
        self.label_2.setStyleSheet("QPixmap pix(\"Logo.jpeg\");\n"
"fLabel->setPixmap(pix);\n"
"fLabel->setStylesheet(\"border-radius: 1x;\");")
        self.label_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("Logo.jpeg"))
        self.label_2.setScaledContents(True)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login Form", None))
        self.u_name_label.setText(_translate("Dialog", "Username", None))
        self.pass_label.setText(_translate("Dialog", "Password", None))
        self.signup_btn.setText(_translate("Dialog", "Sign up", None))
        self.pushButton_2.setText(_translate("Dialog", "Forgot Password ?", None))
        self.label.setText(_translate("Dialog", "Create Account ", None))
        self.login_btn.setText(_translate("Dialog", "Login", None))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
